### ISSUE TITLE
Used hash is not added before being used

### ISSUE THREAD

**Issue by dignifiedquire** [whyrusleeping/ipfs-whatever#6]
The base hash used here: https://github.com/whyrusleeping/ipfs-whatever/blob/master/main.go#L64 seems to not be added before being used. Not sure where it comes from, would be great if it would be added in the setup process as js-ipfs does not have this object by default.

**Comment by dignifiedquire** [comment]
@whyrusleeping ^^

**Comment by Kubuxu** [comment]
It is empty directory hash, we ship it with default repo or it is part of some optimization path in go-ipfs.

**Comment by dignifiedquire** [comment]
I see thanks

**Comment by dignifiedquire** [comment]
I still think it would be good to not rely on its existence.

**Comment by Kubuxu** [comment]
It is added as part of files api as it is default root directory and it is used by many more processes internally too.

I would just suggest js-ipfs add construct like that to its default repo, or add following object to the repo `{"Links":[],"Data":"\u0008\u0001"}` before running tests.

**Comment by whyrusleeping** [comment]
@dignifiedquire Yeah, js-ipfs should create and add this object during init. A large number of different processes assume this exists, and it saves a lot of time if we don't have to constantly check `if not exists, create and add thing`

**Comment by dignifiedquire** [comment]
Okay thanks, will add this to js-ipfs
